apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tf-test-job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
   spec:
     template:
       spec:
         containers:
         - name: job
           image: gcr.io/kr-gcp-ee/kr-tf2-gpu
           args:
           - /bin/sh
           - -c
           - echo waiting for ...; sleep 20; /workspace/go.sh; sleep 5s; echo exiting...; date
           resources:
              limits:
                nvidia.com/gpu: 1
         restartPolicy: Never


